# 在包目录执行: make -f Makefile.prepare prepare
# 编译 C 版 pushbot 到 root/usr/bin/pushbot/pushbot（无需 Go）
prepare:
	$(MAKE) -C pushbot-c clean all
	mkdir -p root/usr/bin/pushbot
	cp pushbot-c/pushbot root/usr/bin/pushbot/pushbot

.PHONY: prepare
